(function($) {
	$.userMsg = $.extend({
		'1400':'Paremeter can not be empty.',
		'1401':'Login may only contain alphanumeric characters or single hyphens, and cannot begin or end with a hyphen.',
		'1402':'The user name is in used.',
		'1403':'The email is in used.',
		'1404':'Invalid email address.',
		'1405':'Password needs 7 characters and at least one number.',
		'1406':'The old and new password can not be the same.',
		'1407':'The old and new email can not be the same.',
		'1408':'Paremeter invalid.',		
		'1500':'Oh snap! Something went wrong!',
		'1501':'Hi, please <a href=\"/user/signin#/editor\" class=\"alert-link\">sign in</a>.',
		'1503':'User name or password invalid.',
		'1504':'Wrong password.',
		'1506':'Email address unfound.',
		'1507':'Verify failure!<ul><li><a href=\"/user/signin#/editor\" class=\"alert-link\">sign in</a> to resend a verify email.</i><li><a href=\"/user/forgot\" class=\"alert-link\">Forgot password</a> to resend.</li></ul>',
		'1508':'Verify code expired.<ul><li><a href=\"/user/signin#/editor\" class=\"alert-link\">sign in</a> to resend a verify email.</i><li><a href=\"/user/forgot\" class=\"alert-link\">Forgot password</a> to resend.</li></ul>',
		'verify_success':'Well done!You got a real account,please <a href=\"/user/signin#/editor\" class=\"alert-link\">sign in</a>.',
		'send_forgot_success':'We have sent you a email, please check your inbox, then reset your password.',
		'reset_pass_success':'Reset your password success!',
		'send_verify_success':'A email has sent to you, please check your inbox to verify.',
		'changemail_success':'A email has sent to your new email address, please check to verify.',
		'changpass_success':'New password was setted!',
		'userinfo_success':'Profile updated!',
		'unknown':'Something went wrong!',
		'done':'Done.',
		'loading':'Loading...'
	}, $.userMsg);
})(window.jQuery||this);